services:
  - type: web
    name: rastus-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        sync: false
      - key: FLW_CLIENT_ID_SANDBOX
        sync: false
      - key: FLW_SECRET_KEY_SANDBOX
        sync: false
      - key: FLW_WEBHOOK_SECRET_HASH
        sync: false
      - key: FLW_API_BASE_URL
        sync: false
      - key: FLW_REDIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        sync: false
